name: Cleanup Old Images
on:
  schedule:
    - cron: "15 1 * * 0" # 01:15 UTC по Воскресеньям
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}

permissions: {}

jobs:
  delete-older-than-90:
    name: Cleanup
    runs-on: ubuntu-latest
    permissions:
      packages: write # требуется для настройки прав доступа к репозиторию
    steps:
      - name: Delete Images Older Than 90 Days
        uses: dataaxiom/ghcr-cleanup-action@cd0cdb900b5dbf3a6f2cc869f0dbb0b8211f50c4 # v1.0.16
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          packages: hyprland-dx,hyprland-nvidia-dx,niri-dx,niri-nvidia-dx,river-dx,river-nvidia-dx,sway-dx,sway-nvidia-dx
          older-than: 90 days
          delete-orphaned-images: true
          keep-n-tagged: 7
          keep-n-untagged: 7